### ISSUE TITLE
Error in last step

### ISSUE THREAD

**Issue by KunFang93** [HenrikBengtsson/TopDom#14]
Hi, Prof. Bengtsson

I have run topdom smoothly until the last step and have this error message:
......
[1] "-- Done!"
[1] "-- Filtering False Positives"
[1] "-- Done!"
[1] "Step 3 Running Time :  5.09800000000018"
[1] "Step 3 : Done!"
Error in ret[i, "from.id"]:ret[i, "to.id"] : NA/NaN argument

I was wondering what might cause this problem and how could I solve it? Is this error result from no tads detected?  Thanks a lot!

Kun

**Comment by HenrikBengtsson** [comment]
Please see the pinned https://github.com/HenrikBengtsson/TopDom/issues/11

**Comment by KunFang93** [comment]
make coordinate start from 0 solve me problem.
